### ISSUE TITLE
Correct integer rounding when using GPU dedispersion

### ISSUE THREAD

**Issue by MSnelders** [thepetabyteproject/your#109]
At the moment the CPU de-dispersion rounds the bin shifts to the _nearest_ integer, see e.g. line 318 of https://github.com/thepetabyteproject/your/blob/324839c3ce412411f89352fd2161ca0686d3bac1/your/candidate.py.

The GPU dedispersion only broadcasts the number of bin shifts to int, which will always round the float down. 
To make the methods more consistent with each other I suggest changing lines 312-317 of https://github.com/thepetabyteproject/your/blob/324839c3ce412411f89352fd2161ca0686d3bac1/your/candidate.py 

from

```
delay_time = int(
                    4148808.0
                    * dms
                    * (1 / (self.chan_freqs[0]) ** 2 - 1 / (self.chan_freqs) ** 2)
                    / 1000
                )
```
                
to

```
delay_time = int(round(
                    4148808.0
                    * dms
                    * (1 / (self.chan_freqs[0]) ** 2 - 1 / (self.chan_freqs) ** 2)
                    / 1000
                ))
```

**Comment by devanshkv** [comment]
Sounds good. Would you please send a PR for the same?

**Comment by MSnelders** [comment]
Send PR request.
