### ISSUE TITLE
RuntimeError: nbits=1 not supported

### ISSUE THREAD

**Issue by mabaisen** [thepetabyteproject/your#116]
Hello, when i run your tutorial about "Candidate class to analyse single pulses".
i have the problem below:
Traceback (most recent call last):
  File "/home/mbs/Desktop/mycode/fetch-tf2/your_candmaker.py", line 40, in <module>
    cand.get_chunk()
  File "/home/mbs/miniconda3/envs/rdkit-smiles/lib/python3.7/site-packages/your/candidate.py", line 218, in get_chunk
    data = self.get_data(nstart=nstart_read, nsamp=nsamp_read)
  File "/home/mbs/miniconda3/envs/rdkit-smiles/lib/python3.7/site-packages/your/your.py", line 255, in get_data
    data = self.formatclass.get_data(self, nstart, nsamp, pol=pol, npoln=npoln)
  File "/home/mbs/miniconda3/envs/rdkit-smiles/lib/python3.7/site-packages/your/formats/pysigproc.py", line 306, in get_data
    self._mmdata[int(b0) : int(b1)], dtype=self.dtype
  File "/home/mbs/miniconda3/envs/rdkit-smiles/lib/python3.7/site-packages/your/formats/pysigproc.py", line 251, in dtype
    raise RuntimeError("nbits=%d not supported" % self.nbits)
RuntimeError: nbits=1 not supported

My fil header is below:
Unified Header:
  "basename": "BJ0009_025C1"
  "bw": -288.0
  "center_freq": 1374.0
  "dec_deg": -40.98771722222223
  "dtype": "uint8"
  "fch1": 1516.5
  "filelist": [
    "data/BJ0009_025C1.fil"
  ]
  "filename": "data/BJ0009_025C1.fil"
  "foff": -3.0
  "format": "fil"
  "frequency_decimation_factor": 1
  "gb": -20.446928712599487
  "gl": 176.3830098025743
  "native_foff": -3.0
  "native_nbits": 1
  "native_nchans": 96
  "native_nspectra": 2121728.0
  "native_tsamp": 0.000125
  "nbits": 8
  "nchans": 96
  "npol": 1
  "nspectra": 2121728
  "poln_order": "I"
  "ra_deg": 287.1500545833334
  "source_name": "Unknown"
  "time_decimation_factor": 1
  "tsamp": 0.000125
  "tstart": 51934.01997685185
  "tstart_utc": "2001-01-25T00:28:46.000"

Could you help me what's the problem i have encountered.

**Comment by devanshkv** [comment]
As mentioned in the error, `nbits=1` is not supported. If you can contribute to the package and send a PR, we will happily incorporate it.

One trick would do would be to add `np.bool_` for nbits=1 here: https://github.com/thepetabyteproject/your/blob/e342da8f14cbb8634357e16a132f8444f962e6ea/your/formats/pysigproc.py#L244-L251

**Comment by devanshkv** [comment]
@mabaisen, can you share a sample 1-bit filterbank?

**Comment by mabaisen** [comment]
> 
Thank you for your help. I download the filterbank from "https://data-portal.hpc.swin.edu.au/dataset/parkes-frbs-archival-data".
I used the first filterbank in FRB010125.tar.gz run your_candmaker
