### ISSUE TITLE
Subband search in your_heimdall

### ISSUE THREAD

**Issue by KshitijAggarwal** [thepetabyteproject/your#21]
It would be useful to add in the option to do subband search in `your_heimdall` either based on number of subbands or by channel ranges.

**Comment by KshitijAggarwal** [comment]
I think https://github.com/thepetabyteproject/your/issues/29 is the first step towards this. `Writer` already has options to select frequency channels. So once dada is integrated with `Writer`, it should be easier to do a subband search. Would require multiple Heimdall instances, but that can probably be handled with a simple outer loop.

**Comment by devanshkv** [comment]
Done with 28eb526997d1e59d4f380438d56b71a094affb92.
