### ISSUE TITLE
Black it!

### ISSUE THREAD

**Issue by devanshkv** [thepetabyteproject/your#33]
We should [Black](https://github.com/psf/black) our code.

[Here](https://www.youtube.com/watch?v=esZLCuWs_2Y&feature=youtu.be) is why!

**Comment by KshitijAggarwal** [comment]
It looks pretty useful. This [document](https://github.com/psf/black/blob/master/docs/the_black_code_style.md) and their code itself looks cleaner. I'd still be a bit cautious about using it. Need to dig around some more.

**Comment by devanshkv** [comment]
@KshitijAggarwal just black it!

**Comment by devanshkv** [comment]
Done!
