### ISSUE TITLE
clearing shared memory 

### ISSUE THREAD

**Issue by KshitijAggarwal** [thepetabyteproject/your#38]
In some cases your_heimdall either doesn't clear the shared memory when exiting, or gives an error if shared memory is already used by something. 

can mention somewhere that this can be used to clear the shared memory: 
https://roadha.us/2011/09/kill-all-shared-memory-segments-in-linux.html

**Comment by devanshkv** [comment]
Does the process exit with an error? Do is there a reproducible example?
