### ISSUE TITLE
median_absolute_deviation is deprecated

### ISSUE THREAD

**Issue by devanshkv** [thepetabyteproject/your#43]
your/utils/rfi.py:77: DeprecationWarning: `median_absolute_deviation` is deprecated, use `median_abs_deviation` instead!

  To preserve the existing default behavior, use
  `scipy.stats.median_abs_deviation(..., scale=1/1.4826)`.
  The value 1.4826 is not numerically precise for scaling
  with a normal distribution. For a numerically precise value, use
  `scipy.stats.median_abs_deviation(..., scale='normal')`.

    std = 1.4826 * stats.median_absolute_deviation(sk_c)

**Comment by KshitijAggarwal** [comment]
uh oh, seems like `median_absolute_deviation` never actually was returning the MAD value, it was already returning std. See [this](https://github.com/scipy/scipy/issues/11090). This is why they deprecated that function. 
but this is very bad, as the std deviation calculations we've done so far are incorrect, or rather higher by a factor of 1.4826.

**Comment by devanshkv** [comment]
@jkania7 @josephwkania might want to have a look at this and run some tests.

**Comment by devanshkv** [comment]
Done with 939db5eff7c87f0f28bcda4fa2a02d224482074e.
