### ISSUE TITLE
Error in writer.py

### ISSUE THREAD

**Issue by ReshmaAnnaThomas** [thepetabyteproject/your#45]
**Describe the bug**

your_writer.py gives a type error. 

**To Reproduce**
```your_writer.py -v -f *fits -t fil -r -sksig 4 -sgsig 4 -sgfw 15 ```

**Screenshots**

<img width="1121" alt="Screen Shot 2020-10-14 at 2 23 03 PM" src="https://user-images.githubusercontent.com/56050319/96046443-801d5080-0e41-11eb-9004-1b20fc0e295f.png">

**Comment by devanshkv** [comment]
I've fixed it in my local version but haven't pushed yet. Quick way around is add `--nstart 0` to your command. I'll try to push my changes tonight.

**Comment by ReshmaAnnaThomas** [comment]
Okay! Thanks!

**Comment by devanshkv** [comment]
Fixed with 13233cf662e3f09a08d085b6f3322140330a139f.
