### ISSUE TITLE
Move to another CI?

### ISSUE THREAD

**Issue by devanshkv** [thepetabyteproject/your#50]
Should we consider moving to another CI service like Circle or Travis? Github Actions keep breaking.
I ran the action associated with the commit 136e2cd in a brand new conda env, and it works just fine.

**Comment by KshitijAggarwal** [comment]
I seem to have tracked down what's happening (maybe). This is also causing our pip install git+https://github.com/thepetabyteproject/your.git to fail. 

SciencePlots require matplotlib while installing. It requires matplotlib already installed. Using pip -r requirements.txt installs all packages together, not serially. So even if matplotlib is written before SciencePlots, it won't be present when SciencePlots is being installed. One thing still not clear to me is that SciencePlots already has matplotlib in its install_requires. So pip should first install matplotlib first, before it tries to run the setup.py of SciencePlots. 

A possible discussion of something similar is here: https://github.com/pypa/pip/issues/1386 

The solution is to somehow install matplotlib before we try to install SciencePlots.

**Comment by KshitijAggarwal** [comment]
Removed SciencePlots with https://github.com/thepetabyteproject/your/commit/97e3f86819d46c046c4dfaba6f13a2a1e9f1ccd4, and everything works now.
