### ISSUE TITLE
Unknown header keywords shouldn't cause a crash

### ISSUE THREAD

**Issue by shamichatterjee** [thepetabyteproject/your#56]
**A filterbank file containing custom keywords crashes the reader**.

Consider, e.g., https://data.caltech.edu/records/1647:
> We note that we use a custom filterbank header that includes the following keys in addition to the standard filterbank header keys: 
> MJD_hour - The hour (in MJD-7hr) that the (typically 5 hr long) observing track started. 
> ...
>  start_sample - The sample of the first time sample contained in the filterbank file. 

When trying to read this filterbank file with YOUR:
`import your`
`fil_file = 'candidate_ovro_20200428.fil'`
`dobj = your.Your(fil_file)`

> KeyError: 'start_sample'

**Expected behavior: the reader should provide a warning and continue reading the file.**
e.g., 
> "Unknown keyword: start_sample"

It's not ideal, but crashing with KeyError is worse.

**Comment by KshitijAggarwal** [comment]
Interesting. Thanks for pointing it out. 7618df84cf8bc9838a966735d92789126d27943d and ccfd38f287cd1382a4b212ca9c84fb83e14cd5b2 should fix it. 

Feel free to close this issue if it works for you now. 

Implementation note: Their header contains many custom parameters for which we don't know the size of their values. So we have assumed it to be 4 bytes, and if it is larger than 4 bytes, we just keep taking steps of 4 bytes till we reach a header parameter which makes sense.

**Comment by shamichatterjee** [comment]
Yes, this solution works quite well, thanks!
