### ISSUE TITLE
Can't open PSRFITS made from PSRCHIVE's psrconv 

### ISSUE THREAD

**Issue by mef51** [thepetabyteproject/your#58]
Apologies if this is a simple misunderstanding, a lot of the PSRFITS/PSRCHIVE documentation is offline/incomplete making this hard to debug.

I was trying to open the [psrchive files](http://www.alert.eu/FRB121102/) from [Oostrum et al. 2020](https://arxiv.org/pdf/1912.12217.pdf), which are in `*.ar` format by using `psrconv` to convert to PSRFITS and then using `your`

The following error gets thrown (`ValueError: File 'R1_B01.fits' does not appear to be PSRFITS!`) and is due to [`is_PSRFITS`](https://github.com/thepetabyteproject/your/blob/master/your/formats/psrfits.py#L825) reading the "OBS_MODE" field of the fits file being set to "PSR" instead of "SEARCH". I'm not sure what the difference is, but bypassing this condition to force your to try and read it results in other format errors.

If this is a problem with the data itself or a bug in psrconv feel free to close.
Is there some other way to read `*.ar` files with your?

**Comment by devanshkv** [comment]
We only support the `SEARCH` mode data. I think [pypulse](https://github.com/mtlam/PyPulse) can be used for `.ar` files.

**Comment by mef51** [comment]
workaround was to use `psrconv` to convert .ar files to fits files and use `pypulse` to read those fits files
