### ISSUE TITLE
Conversion ASCII 2-d array to psrfits

### ISSUE THREAD

**Issue by praana** [thepetabyteproject/your#69]
Hi,
I wanted to convert a two column ascii file into psrfits format. You have mentioned how to write a filter file from scratch. Is the process similar or I need do something else? 
After conversion, I want to run psrchive commands on the psrfits file. So I also need to know how to add parameters to the file while I convert it.

Let me know how this issue can be solved...

Clear Skies,
Pranav

**Comment by KshitijAggarwal** [comment]
Hi, 
We currently do not have the functionality to write a psrfits file from scratch. In principle, it is possible to do that by making some modifications to the `Writer` class. 
To do so, you would first have to create a `Your` object by using an existing psrfits or Filterbank file, then create a `Writer` object using this `Your` object, modify the necessary attributes of the `Writer` and `Your` objects so that the output psrfits header contains correct information, and then modify `to_fits` function so it uses an input data array instead of using data from `get_data_to_write`.  

Also, to add header parameters to the psrfits file that are different from the header parameters currently written, you will have to modify [`fitswriter.py`](https://github.com/thepetabyteproject/your/blob/master/your/formats/fitswriter.py)

**Comment by KshitijAggarwal** [comment]
I see. I have not worked with `.gpt` files, so I am not sure how to convert those to psrfits or filterbank format. A quick google search for GMRT `.gpt` files returned this paper ([here](https://arxiv.org/abs/2007.02930)). Figure 1 of this paper shows a conversion from `.gpt` to Filterbank files. Maybe you can contact the authors and ask for the conversion script? Once you have Filterbank files, then you can directly use `Writer` to convert them to psrfits.

**Comment by praana** [comment]
Thanks!
I will try doing this and let you know what happens...

Even if I don't know how to convert .gpt file to .fil file, I still know
that my data is a two dimensional array. Can I separate out the two columns
of data first using numpy and then load that data into .fil file while
constructing the filter Bank file?

Clear Skies,
Pranav

**Comment by devanshkv** [comment]
Yes! you can do that easily. Just follow [this](https://thepetabyteproject.github.io/your/ipynb/Writer/#writing-filterbanks-from-scratch), add the appropriate header and replace `data_written` with your NumPy array.

**Comment by praana** [comment]
Hi,
I am now able to convert my ascii file to equivalent fits file.

When I display this file in psrchive using the psredit command, I am
getting the list of parameters where the telescope name is 'VLA',
project_id is 'awesome' etc.
How can I change these parameters since they are not mentioned while
writing the filter file. I just append them while constructing the filter
files?

Also, the file name extension is .fits, is there any need to convert this
again into psrfits using psrconv?

Clear Skies,
Pranav

**Comment by devanshkv** [comment]
As @KshitijAggarwal said earlier there is no direct way of doing it, you would have to modify [fitswriter.py](https://github.com/thepetabyteproject/your/blob/master/your/formats/fitswriter.py)

You can have to edit 
- project ID and source info at  https://github.com/thepetabyteproject/your/blob/270254a562fff6b94bb2805d56dda64ad8343c37/your/formats/fitswriter.py#L26-L34
- the telescope and its position at https://github.com/thepetabyteproject/your/blob/270254a562fff6b94bb2805d56dda64ad8343c37/your/formats/fitswriter.py#L50-L53

I am not sure what you mean by "filter files". psrfits files have `.fits` extension so it should be fine.

**Comment by praana** [comment]
Hi,
Thanks for guiding me to this code to modify header information.

The filter files is basically the .fil file or the sigproc object I created
where I have put my data array.

The GitHub code link you shared to modify the header information, do I just
need to copy that out in my previous code at the beginning and then
continue with creating the sigproc object, write it to fits and so on.

Where exactly I need to use this header info code?

Clear Skies,
Pranav

**Comment by devanshkv** [comment]
I am a bit confused here. I assume you have made the filterbank files (it's typically called filterbank instead of a filter file). I think then you are trying to convert from filterbank to psrfits and then getting the incorrect header.

If this is the case, yes, this would happen because we a few things (like telescope name, project ID, etc.) hardcoded for now. The quick and dirty way of solving this is to clone the repo, modify these things by hand, reinstall and then run.

The proper way of doing this is to add stuff in [writer](https://github.com/thepetabyteproject/your/blob/270254a562fff6b94bb2805d56dda64ad8343c37/your/writer.py#L19) class and [fitswriter.py](https://github.com/thepetabyteproject/your/blob/master/your/formats/fitswriter.py) to handle this properly.

In case you take the latter route, we would be happy to help you navigate this and would really appreciate your contributions.

**Comment by praana** [comment]
Hi,
I should probably call them filterbank files rather than filter files, my
apologies...

I'm essentially writing filterbank files by defining a sigproc object and
then write this object to psrfits using the Writer class followed by the
steps as mentioned in the GitHub code.

I would really appreciate it if you could navigate me through how I can
modify the header information specifically the telescope name, project
name,etc.

I'm really very unaware of how I clone the code rebuild the files etc. It
would really help if you could help me with this :)

Clear Skies,
Pranav

**Comment by devanshkv** [comment]
First, uninstall your installation using `pip uninstall your`. Next, we will get a local copy of the source code
``` bash
git clone https://github.com/thepetabyteproject/your.git
cd your/
```.`
Now you can edit the `your/formats/fitswriter.py` file where you would have to edit the following with your own details.
- project ID and source info at  https://github.com/thepetabyteproject/your/blob/270254a562fff6b94bb2805d56dda64ad8343c37/your/formats/fitswriter.py#L26-L27
- the telescope and its position at https://github.com/thepetabyteproject/your/blob/270254a562fff6b94bb2805d56dda64ad8343c37/your/formats/fitswriter.py#L50-L53

Once done, run
```bash
python setup.py install
```

This installs the *edited* version of your, and now you convert these files to psrfits, it should work fine.

While this is the quick and dirty way, we would really appreciate it if you can contribute towards the proper implementation and be happy to guide you towards that.

**Comment by praana** [comment]
Hi,
Thanks for these instructions. I will try this out and let you know.

I would be really happy to contribute towards the proper implementation of
this. Let me know how this can workout!

Clear Skies,
Pranav

**Comment by devanshkv** [comment]
Hi @praana, here are the steps for doing it properly:

- First [fork](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo) the repository.
- Git clone your fork locally and start editing as follows
- Add the following arguments in `initialize_psrfits`https://github.com/thepetabyteproject/your/blob/270254a562fff6b94bb2805d56dda64ad8343c37/your/formats/fitswriter.py#L262-L271 and also add some default values for `telescope`, `ant_x`, `ant_y`, `ant_z`, `observer`, `proj_id`. Make sure you add proper documentation in the docstring as well.
- Similar to the `fill_freq_info` function, create another function in  `fitswriter.py` to take the above values and update them https://github.com/thepetabyteproject/your/blob/270254a562fff6b94bb2805d56dda64ad8343c37/your/formats/fitswriter.py#L74-L78
- call that function after https://github.com/thepetabyteproject/your/blob/270254a562fff6b94bb2805d56dda64ad8343c37/your/formats/fitswriter.py#L368
- Now add the same arguments with default values to https://github.com/thepetabyteproject/your/blob/270254a562fff6b94bb2805d56dda64ad8343c37/your/writer.py#L315
- And modify this function appropriately https://github.com/thepetabyteproject/your/blob/270254a562fff6b94bb2805d56dda64ad8343c37/your/writer.py#L337-L346
- Once done, install this edited copy as mentioned above and see if things are running as they should be running.

If everything is fine [commit](https://guides.github.com/activities/hello-world/#commit) and send us a [PR](https://guides.github.com/activities/hello-world/#pr). Let us know if you have any questions.

**Comment by praana** [comment]
Hi,
Thanks for providing me this. At the moment, I dont have the real
parameters of the telescope and observation specifications, but I can put
some dummy parameters and see...

Meanwhile, I tried using psrchive commands on the fits file I created
earlier. The fits file must contain my intensity vs phase data along with
the header information. When I run psredit command, I can see all the
header information. However, when I run psrplot to visualize my pulse
profile, I get a blank pgplot window. Is there an issue with the data array
not getting loaded properly into the fits file?

Clear Skies,
Pranav

**Comment by devanshkv** [comment]
I am sorry but I am not a `psrchive` expert and I can't help with this.

**Comment by praana** [comment]
Hi,
I think I get what eror psrchive is giving me while plotting the pulse
profiles.
When I run the command 'psredit' on the fits file, it gives me all the
parameter information of that file. In this information there are four
distinct parameters as follows:
1) nbin : number of phase pulse bins
2) nchan: number of frequency channels
3) npol: number of polarizations
4) nsubint: number of sub integrations or total number of pulses folded in
this profile

I am guessing that the numerical values for these parameters are put in
with respect to VLA data.

I also viewed the github link you sent me to change the telescope name,
position,etc. I can see some functions in this code to define the
nchan,nbin,npol and nsubint.
Can I edit these values and if so how will it be possible? Can you guide me
through this?


Clear Skies,
Pranav

**Comment by devanshkv** [comment]
You use the same technique as mentioned in https://github.com/thepetabyteproject/your/issues/69#issuecomment-826160346 to edit these values.

**Comment by KshitijAggarwal** [comment]
Also, I suspect that you need FOLD mode data. We can only write SEARCH mode data in psrfits files. 
You can take a look at https://github.com/PsrSigSim/PsrSigSim to write FOLD mode data.
