### ISSUE TITLE
output dir issue with your_writer.py

### ISSUE THREAD

**Issue by devanshkv** [thepetabyteproject/your#70]
**Describe the bug**
`your_writer.py` writes data in `.` instead of `./` when no output-dir is given

**To Reproduce**
`your_writer.py -f test.fits -t fil`

**Expected behaviour**
should create `test.fil` instead of `.test.fil`

**Comment by KshitijAggarwal** [comment]
Fixed with f34ae0906410ca441124f24c22fb67536daae3b1
