### ISSUE TITLE
YOUR is not reading in headers of 4bit data files properly

### ISSUE THREAD

**Issue by sahilatri126** [thepetabyteproject/your#84]
**Describe the bug**
I am using YOUR to read in and process Arecibo 4 bit data, On using your_header.py I am getting wrong values of fc1 (lowest frequency), Bandwidth and channel width. After having a look at the frequency vs time plot of one file using your_h5plotter.py , I found that the bandpass is being read in wrong. We can see the correct values by simplly using readfile command of presto.

**Expected behavior**
I am using YOUR to run heimdall, psrdada,fetch etc to recover pulsars. I ran YOUR on some known pulsar file and I could recover those pulsars as well, but the DM value found in the plot is very much deflected from the real value of the pulsar. In one specific pulsar case the real DM is 50 but using YOUR I am getting DM around 34 ( B0525+21 pulsar.). I am expecting all values to be read in correctly and as a result the DM also must be closer to the actual value.

**Screenshots**

Here you can compare the values produced my your_header.py and readfile (presto), most of the values are being read in wrong here by your_header.py, which eventually is affecting my results. You Can see in the final plot that all values are wrong and the DM is also deflected alot from the real value. The screenshot are of a data file of B2110+27 pulsar.
The correct DM of this pulsar is 25.11 but from the plot we can see the value we are getting is too much deflected.
![Screenshot from 2021-10-09 11-26-39](https://user-images.githubusercontent.com/93368118/139390021-78af620e-8a95-4e81-9cb8-b6e7b7f1e1f2.png)
![Screenshot from 2021-10-09 11-26-54](https://user-images.githubusercontent.com/93368118/139390026-a9e94eed-1a73-4896-8905-813fdf35945d.png)
![cand_tstart_56608 938645833332_tcand_57 4765000_dm_15 12360_snr_7 21403](https://user-images.githubusercontent.com/93368118/139390497-c34f75b8-9e2b-407a-b7d1-496781edd3df.png)

**Versions (please provide the versions of the the following packages):**
These are versions of packages in the specific conda environment I am using.
- your             0.6.5 
- matplotlib     3.3.4 
- numpy          1.19.5
- h5py              1.10.6
- scikit-image   0.17.2 
- scipy              1.5.4 
- numba            0.53.1
- astropy             4.1
- pandas             1.1.5 
- rich                  10.4.0 

**Additional context**
I suspect that it is specific to 4 bit data files

**Comment by devanshkv** [comment]
Can you share the file path?

**Comment by devanshkv** [comment]
fixed with #82.
