### ISSUE TITLE
Fits to Filterbank conversion using your_writer  has issue

### ISSUE THREAD

**Issue by sahilatri126** [thepetabyteproject/your#92]
I am processing AO327 data which is in a 4-bit data format. I used your_writer to convert those fits file to filterbank format so that I can later decimate it using sigproc.  But the filterbank files produced by your_writer.py, when run on sigproc for decimation is showing " ERROR: input data to decimate is not in the filterbank format" and as a result I am not able to decimate those files. 

To cross check I converted those files from fits to filterbank format using psrfits2fil.py tool of PRESTO. The filterbank files generated using this are accepted by sigproc for decimation and not showing any error.

On looking at the details of the filterbank file produced by psrfits2fil and your_writer.py using readfile command of PRESTO. I found that many values of frequency and other things are mentioned wrong in the filterbank file produced by your_writer.py

To check if the issue is only with the 4-bit data file or not. I did the same process on 16-bit data files and I am getting the same error.

**To Reproduce**
your can simply go inside /hyrule/data/ao327/4bitdata and run it on any file.
for some 16 bit files you can find it in /hyrule/data/users/satri/16_bit_test/ in the bowser

**Expected behavior**
your_writer.py must convert the files from fits to filterbank  format properly so that it show all the details of frequencies correct and the filterbank format is proper and Accepted by sigproc for decimation.

**Screenshots**
![error](https://user-images.githubusercontent.com/93368118/150624938-40311356-072f-415a-bd23-9532decb1b81.png)
![sigproc_fil](https://user-images.githubusercontent.com/93368118/150625010-4834bb6f-06bc-4834-87a1-54cae19c0fb3.png)
![your_writer_fil](https://user-images.githubusercontent.com/93368118/150625016-31a9bbe9-8d7a-42c9-8e9f-6705c4f28a0a.png)
![16-bit_test](https://user-images.githubusercontent.com/93368118/150625241-15de1faa-a8db-42ed-a970-8c25ce62bf10.png)

**Versions (please provide the versions of the the following packages):**
- your -0.6.6

**Additional context**
Let me know if any other information is required from my side.

**Comment by devanshkv** [comment]
@sahilatri126 please run the above again with the `--verbose` flag and let us the outputs. Please also post the outputs of `your_header.py`.

**Comment by sahilatri126** [comment]
![file1](https://user-images.githubusercontent.com/93368118/150647769-f93bb215-b54c-4c7c-84c8-f31720d7cbaa.png)
![file2](https://user-images.githubusercontent.com/93368118/150647773-e386a8a4-70b5-42ec-971e-7a22a8c4d24c.png)
![verbose](https://user-images.githubusercontent.com/93368118/150647780-17398fb6-53dc-4d2b-9984-0ebf310576bd.png)

I did not see abything after using --verbose option I am attaching the your_writer log file.
[your_writer_2022_01_22_16_13_12_702063.log](https://github.com/thepetabyteproject/your/files/7918764/your_writer_2022_01_22_16_13_12_702063.log)

**Comment by devanshkv** [comment]
These don't make any sense. I don't understand what's this converted file is, how it was converted and what should it actually look like.

1. `your_header.py` output of the original psrfits file.
2. `your_header.py` output of the file converted filterbank file using your.

And kindly label the screenshots so that we understand what image corresponds to what.

**Comment by sahilatri126** [comment]
Ok, This converted file is the filterbank file generated after I run your_writer.py on a file  4bit_puppi_58888_Strip25_0068.0001.fits.
It was converted simple using " your_writer.py -f filename -t fil" 
I am just getting error that it is not in filterbank format when I use this file for decimation in sifproc, files converted using psrfits2fil are not giving such error, so I consider the details of the data shown by that file is correct and if I cross check it with your_writer converted file I see that lowest frequency mentioned there is not matching with the psrfits2fil converted fil file. 
I am not sure what is actually wrong with this fil format file generated but I just don't want to get error when I use sigproc on it for decimation. It shows the file is not a filterbank.

This is the original fits file header.
![Screenshot from 2022-01-22 23-02-26](https://user-images.githubusercontent.com/93368118/150649283-5eb969f8-56a8-481f-9f52-1df8de0606ce.png)

Thsi is the generated filterbank
![Screenshot from 2022-01-22 23-21-57](https://user-images.githubusercontent.com/93368118/150649904-61b4b63c-4838-4171-8cd3-3198d596a43c.png)
 file header

**Comment by KshitijAggarwal** [comment]
@sahilatri126 We have made a fix and issued a new release. Install version 0.6.7 and confirm it from your end.
