### ISSUE TITLE
Issues of your_heimdall.py

### ISSUE THREAD

**Issue by Shinnnosuke2** [thepetabyteproject/your#95]
When I run your_heimdall.py, I have memory and cuda issues, and can not get .cand file. Please see the below message.
(psrdada and psrdada-python was already installed.)

your_heimdall.py -dm 560 570 -f *.fits

Created DADA data block with nbufs=8 bufsz=536870912 nread=1
Created DADA header block with nhdrs = 8, hdrsz = 4096 bytes, nread=1
ipcbuf_lock: shmctl (shmid, SHM_LOCK): Cannot allocate memory
Could not lock DADA data block into RAM
Reading... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--Createing PSRDADA client
Connecting to ring buffer
Waiting for next header / data
Reading... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--processing beam 1
Reading... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--Could not setCudaDevice to 0: forward compatibility was attempted on non supported HW
ERROR: Pipeline creation failed
       Unknown error. Please contact the author(s).
Reading... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00

Could you tell me how to fix these errors?

Versions 
- your '0.6.7'

**Comment by devanshkv** [comment]
This looks like a hardware issue. I would talk to Joe Glaser about (joe.glaser@nanograv.org).
